# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'b4979711-5a1a-4dff-800b-628989e66d76'
    pipeline: '9'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'refs/heads/master'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftps://waws-prod-bay-123.ftp.azurewebsites.windows.net/site/wwwroot'
    username: 'WebAgentProStarter\$WebAgentProStarter'
    password: 'Kxd8xgmwRsWqJ5Zex0PTfsee2ZQ3ydnpp9JfepnrKoZZjyfLSgDvQ7dwaxg0'
    rootDirectory: '$(System.ArtifactsDirectory)'
    filePatterns: '**'
    remoteDirectory: '/'
    clean: false
    cleanContents: false
    preservePaths: false
    trustSSL: false